project:
  type: website

website:
  title: "NieuwMount Labs"
  site-url: "https://nieuwmount.com"
  google-analytics: " "
  page-footer:
    left: "2026 Â© NieuwMount.com"
    right:
      - icon: github
        href: https://github.com/
      - icon: X
        href: https://x.com/
      - icon: envelope
        href: https://github.com/
  twitter-card:
    creator: " "
    card-style: summary_large_image
  navbar:
    title: "Digital thinking in AI & Research"
    logo: "logo.png"
    background: "#000000"
    foreground: "#FFFFFF"
    pinned: true
    left:
      - text: "Michael Wang"
        href: index.qmd
        
    right:
      - text: AI tools
        icon: card-checklist
        href: AI-tools/
      - text: Academic prompt
        icon: send
        href: academic-prompt/
      - text: R
        icon: calculator
        href: r/
      - text: Python
        icon: code-slash
        href: python/
      - text: AI news
        icon: newspaper
        href: news/
      - text: AI image prompt
        icon: image
        href: image-prompt/
      - text: Coffee time
        icon: cup-hot
        href: coffee-time/
      - text: About
        icon: info-circle
        href: about.qmd

format:
  html:
    smooth-scroll: true
    theme: [litera, styles.css]
    link-external-icon: false
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    toc: true
    toc-depth: 3
    toc-title: "Contents"
    toc-location: left
    code-link: false
    anchor-sections: true
    code-tools: true
    code-fold: true
    code-block-bg: "#f1f3f5"
    code-block-border-left: "#31BAE9"
    reference-location: margin
    fig-cap-location: margin

comments:
  hypothesis:
    theme: clean
    openSidebar: false
    enableExperimentalNewNoteButton: true

execute:
  warning: false
  message: false